// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjANXDa-rh8a5lRRleL7Dxi1FQH4EbuIM',
    appId: '1:443076891375:web:f36d4007b7369ed407811a',
    messagingSenderId: '443076891375',
    projectId: 'comprobantes-9d044',
    authDomain: 'comprobantes-9d044.firebaseapp.com',
    storageBucket: 'comprobantes-9d044.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQfWZpXLQZJBawebXIUImZQDpuTKguKPo',
    appId: '1:443076891375:android:c9a5af9a0ddc992a07811a',
    messagingSenderId: '443076891375',
    projectId: 'comprobantes-9d044',
    storageBucket: 'comprobantes-9d044.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQCb45XZM0nyw3R23l6SfgGEkqu5dSR5Q',
    appId: '1:443076891375:ios:248bc6a02552f4fa07811a',
    messagingSenderId: '443076891375',
    projectId: 'comprobantes-9d044',
    storageBucket: 'comprobantes-9d044.appspot.com',
    iosBundleId: 'dev.donmanuel.comprobantes',
  );
}
